### ISSUE TITLE
Simplify EtreeParser

### ISSUE THREAD

**Issue by phihag** [hhucn/webvulnscan#22]
EtreeParser doesn't care about the URL, it should be simply given a `warn` or `log` method.

**Comment by rliebig** [comment]
It seems that there is an Issue under Python 3 with the modifications: https://travis-ci.org/hhucn/webvulnscan/jobs/10446465#L149

**Comment by phihag** [comment]
The modification was unrelated to this issue (which is about the logging framework), but the errors under Python 3 are now fixed.

**Comment by rliebig** [comment]
I just tried webvulnscan against vulnsrv, this was the output:

```
Warning: http://localhost:8666/reset HTML Error Unclosed tag <meta>
Warning: http://localhost:8666/mac/login HTML Error Unclosed tag <meta>
Warning: http://localhost:8666/clientauth/secret HTML Error Unclosed tag <meta>
Warning: http://localhost:8666/xss/send HTML Error Unclosed tag <meta> on/msg?id=1 Incorrect Unicode handling in URL 
<other vulnerabilities>
```

However, the [w3c wiki](http://www.w3.org/wiki/HTML/Elements/meta) shows examples where the `<meta>`-Syntax is allowed. I'm not sure if this is behavior is wanted.

**Comment by phihag** [comment]
Are you sure that you're using the newest version of vulnsrv? I cannot reproduce these errors.

**Comment by rliebig** [comment]
Sorry, I didn't notice that there was a update.
