### ISSUE TITLE
Add testing for commandline options.

### ISSUE THREAD

**Issue by rliebig** [hhucn/webvulnscan#23]
It should be possible, to test the command line interface, in order to avoid errors. This should be also done for configuration files.

**Comment by phihag** [comment]
In general, that may be a good idea, but it's somewhat unlikely that automated tests find significant bugs in there. I'd rather focus on other parts of the application, since these tend to be slow as well.

**Comment by phihag** [comment]
Closing for now, until we find an actual bug, we should not test.
