### ISSUE TITLE
Make output order determined

### ISSUE THREAD

**Issue by phihag** [hhucn/webvulnscan#39]
Currently, the order of the default output is random (due to [hash randomization](http://bugs.python.org/issue13703) only being implemented in newer cPython versions, this can only be observed in 3.3+). That can lead to differently sorted outputs even if the whole scanning process is deterministic, which is confusing. We should always have the same order in the output.

**Comment by rliebig** [comment]
Fixed via https://github.com/hhucn/webvulnscan/commit/b289a69d73e45a5878e454a8e12deb0567b387f7
