### ISSUE TITLE
Check for handling of exotic characters

### ISSUE THREAD

**Issue by phihag** [hhucn/webvulnscan#6]
Add a check that the application in question can handle exotic characters and does not break down. In particular, this includes
- [x] Quotes (`"`, `'`)
- [x] Brackets (`<{[()]}>`)
- [x] Ampersands and pipe symbols (`&|`)
- [x] Characters outside of the [BMP](http://en.wikipedia.org/wiki/Basic_Multilingual_Plane#Basic_Multilingual_Plane), such as [this one](http://www.fileformat.info/info/unicode/char/1d550/index.htm)
- [ ] The [NUL character](http://en.wikipedia.org/wiki/Null_character)
- [ ] Byte sequences that are not valid UTF-8

**Comment by rliebig** [comment]
The CLRF-Sequence should also be tested by this attacker.

**Comment by rliebig** [comment]
Ignore my last comment, CLRF deserves a own attacker.
